package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import talen.Language;

import java.io.IOException;
import java.net.URL;
import java.util.InputMismatchException;
import java.util.Locale;
import java.util.ResourceBundle;

import domein.DomeinController;
import exceptions.AlleSpelersReedsAangemeldException;
import exceptions.SpelerNietInDBException;
import exceptions.SpelerReedsAangemeldException;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class MeldAanController extends BorderPane implements Initializable {
	@FXML
	private Label lblMeldAan;
	@FXML
	private Button btnMeldAan;
	@FXML
	private TextField txfMeldAanSpelersnaam;
	@FXML
	private TextField txfMeldAanWachtwoord;

	private ResourceBundle bundle ;

	private DomeinController dc;

	private Language language = Language.getInstance();

	public MeldAanController(DomeinController dc, Locale l) {
		super();
		this.dc = dc;
		ResourceBundle bundle = ResourceBundle.getBundle("talen.ApplicationMessage", l);
		this.bundle = bundle;
		language.stelTaalIn(l.getLanguage(), l.getCountry());
		FXMLLoader loader = new FXMLLoader(getClass().getResource("MeldAan.fxml"), this.bundle);
		loader.setRoot(this);
		loader.setController(this);
		try
		{
			loader.load();
		}
		catch(IOException ex)
		{
			throw new RuntimeException(ex);
		}
	}

	// Event Listener on Button[#btnMeldAan].onAction
	@FXML
	public void btnMeldAanOnAction(ActionEvent event) {
		// TODO Autogenerated
		
		String spelersnaam = txfMeldAanSpelersnaam.getText();
		String wachtwoord = txfMeldAanWachtwoord.getText();
		
		try {
			if(spelersnaam == null || spelersnaam.isBlank() || wachtwoord == null || wachtwoord.isBlank()) 
			{
				throw new InputMismatchException(language.getString("veldenZijnLeeg"));
			}
			
			dc.meldAan(spelersnaam,wachtwoord);
			
			if(!dc.bepaalAlleSpelersAangemeld()) {
				int aantalSpelersMomenteelAangemeld = this.dc.geefSpelersnamen().size();
				this.lblMeldAan.setText(String.format(language.getString("geefSpelersnaam") + " %d:", aantalSpelersMomenteelAangemeld + 1));
				txfMeldAanSpelersnaam.clear();
				txfMeldAanWachtwoord.clear();
			}
			else {
				Scene newScene = new Scene(new AlleAangemeldController(this.dc, this.bundle.getLocale()));
				Stage stage = (Stage) this.getScene().getWindow();
			       stage.setScene(newScene);
			       stage.show();
			}
		} catch (SpelerNietInDBException e) {
			// TODO Auto-generated catch block
			this.exceptionGooien(language.getString("spelerNietInBatabank") + "%n" + language.getString("geefSpelersnaam"));
		} catch (SpelerReedsAangemeldException e) {
			// TODO Auto-generated catch block
			this.exceptionGooien(language.getString("spelerReedsAangemeld") + "%n" + language.getString("geefSpelersnaam"));
		} catch (InputMismatchException e) {
			this.exceptionGooien(language.getString("ongeldigeInvoerSpelersAangemeld") + "%n" + language.getString("geefSpelersnaam"));
		} catch (AlleSpelersReedsAangemeldException e) {
			this.exceptionGooien(language.getString("alleSpelersReedsAangemeld") + "%n" + language.getString("geefSpelersnaam"));
		}
	}

	public void exceptionGooien(String foutmelding) {
		int aantalSpelersMomenteelAangemeld = this.dc.geefSpelersnamen().size();
		this.lblMeldAan.setText(String.format(foutmelding +" %d: ", aantalSpelersMomenteelAangemeld +1));
		this.lblMeldAan.setStyle("-fx-text-fill: red;");
		txfMeldAanSpelersnaam.clear();
		txfMeldAanWachtwoord.clear();
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		int aantalSpelersMomenteelAangemeld = this.dc.geefSpelersnamen().size();
		this.lblMeldAan.setText(String.format(language.getString("geefSpelersnaam") + " %d:", aantalSpelersMomenteelAangemeld + 1));
		
	}
	
	
}
