package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

import java.io.IOException;

import domein.DomeinController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class MeldAanController extends BorderPane {
	@FXML
	private Label lblMeldAan;
	@FXML
	private Button btnMeldAan;
	@FXML
	private TextField txfMeldAanSpelersnaam;
	@FXML
	private TextField txfMeldAanWachtwoord;

	private DomeinController dc;

	public MeldAanController(DomeinController dc) {
		super();
		this.dc = dc;
		FXMLLoader loader = new FXMLLoader(getClass().getResource("MeldAan.fxml"));
		loader.setRoot(this);
		loader.setController(this);
		try
		{
			loader.load();
		}
		catch(IOException ex)
		{
			throw new RuntimeException(ex);
		}
	}

	// Event Listener on Button[#btnMeldAan].onAction
	@FXML
	public void btnMeldAanOnAction(ActionEvent event) {
		// TODO Autogenerated
		
		String spelersnaam = txfMeldAanSpelersnaam.getText();
		String wachtwoord = txfMeldAanWachtwoord.getText();
		if(!(spelersnaam == null || spelersnaam.isBlank()) && !(wachtwoord == null || wachtwoord.isBlank())) 
		{
			dc.meldAan(spelersnaam,wachtwoord);
			if(!dc.bepaalAlleSpelersAangemeld()) {
				txfMeldAanSpelersnaam.clear();
				txfMeldAanWachtwoord.clear();
			}
			else {
				Scene newScene = new Scene(new AlleAangemeldController(this.dc));
				Stage stage = (Stage) this.getScene().getWindow();
		        stage.setScene(newScene);
		        stage.show();
			}
		}
	}
	
	
}
