package gui;

import java.io.IOException;
import java.net.URL;

import domein.DomeinController;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.MenuButton;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import talen.Language;
import java.util.ResourceBundle;

public class StartAanmeldenController extends BorderPane {
	@FXML
	private Button btnStartAanmelden;
	@FXML
	private MenuButton mbtnTextByController;
	private ResourceBundle bundle;
	
	private DomeinController dc;

	public StartAanmeldenController(DomeinController dc) {
		super();
		this.dc = dc;
		FXMLLoader loader = new FXMLLoader(getClass().getResource("StartAanmelden.fxml"));
		loader.setRoot(this);
		loader.setController(this);
		try
		{
			loader.load();
		}
		catch(IOException ex)
		{
			throw new RuntimeException(ex);
		}
	}

	// Event Listener on Button[#btnStartAanmelden].onAction
	@FXML
	public void btnStartAanmeldenOnAction(ActionEvent event) {
		// TODO Autogenerated
		Scene newScene = new Scene(new GeefAantalGebruikersController(this.dc));
		Stage stage = (Stage) this.getScene().getWindow();
        stage.setScene(newScene);
        stage.show();
	}
	
	public void initialize(URL location, ResourceBundle resources) {
		bundle = resources;
		mbtnTextByController.setText(bundle.getString("taalknop"));
	}
}
